import { writeFileSync } from 'node:fs'
import { successfulCombinations } from '../../link-mapping.gen'
import { decodeHtmlEntitiesDeep } from '../../../lib/generators/factbook'
import { jsonParseLiteral } from '../../lib/emit'
import type { FactbookResponse } from '../../../types/response.type'

const OUTPUT_FILE = 'data/factbook.gen.ts'

/**
 * Freeze the CIA Factbook into the repo, once.
 *
 * The `factbook/factbook.json` mirror stopped updating its DATA on 2026-01-22 —
 * every commit since, through 2026-05-17, is a README edit, verified against
 * the GitHub API. So the 194 requests `create-countries-file.ts` made on every
 * run were fetching bytes that had not changed in seven months, and would not
 * change again.
 *
 * Freezing costs nothing that is not already lost, and buys three things: the
 * countries generator drops from ~2.5 minutes to seconds, the build stops
 * depending on a dead repository staying online, and every run becomes
 * byte-reproducible.
 *
 * What still comes from here, after fourteen stats moved to live sources:
 *   - the static facts (land area, highest peak, independence year)
 *   - `infrastructure.rail` and the religion pair, which have no live source
 *     (see issues #146 and #147)
 *   - `economics.exports`, the commodity lists the Made In round grades on
 *   - `name.demonyms`, which `mentionsCountry` uses to scrub country giveaways
 *   - per-country BACKSTOP values for eighteen stats where a multilateral
 *     source has a gap: Cuba's public debt, Taiwan's GDP, and so on
 *
 * Re-run only to re-take the snapshot, which is pointless while the mirror is
 * dead. If it ever resumes, this is the one command that picks it up.
 */

const main = async () => {
  const snapshot: Record<string, FactbookResponse> = {}
  let failed = 0

  for (const { url, isoCode } of successfulCombinations) {
    try {
      const response = await fetch(url)
      if (!response.ok) throw new Error(`HTTP ${response.status}`)
      snapshot[isoCode] = decodeHtmlEntitiesDeep(await response.json())
    } catch (error) {
      failed++
      console.warn(`  ${isoCode}: ${String(error).slice(0, 80)}`)
    }
    const done = Object.keys(snapshot).length + failed
    if (done % 20 === 0) process.stdout.write(`\r  ${done}/${successfulCombinations.length}`)
  }
  process.stdout.write('\n')

  // A partial snapshot would silently blank whole fields for the countries it
  // missed, and the file it overwrites is the only copy. Refuse instead.
  const kept = Object.keys(snapshot).length
  if (kept < successfulCombinations.length - 2) {
    throw new Error(
      `Only ${kept} of ${successfulCombinations.length} countries fetched — refusing to write a partial snapshot`
    )
  }

  writeFileSync(
    OUTPUT_FILE,
    `// Generated by generators/vendors/cia/snapshot-factbook.ts — do not edit by hand.\n` +
      `//\n` +
      `// A FROZEN copy of the CIA World Factbook. The upstream mirror\n` +
      `// (factbook/factbook.json) stopped updating its data on 2026-01-22, so this\n` +
      `// is the last vintage that will ever exist. Re-running the snapshot script\n` +
      `// fetches identical bytes.\n` +
      `import type { FactbookResponse } from '../types/response.type'\n\n` +
      `export const FACTBOOK: Record<string, FactbookResponse> = ${jsonParseLiteral(snapshot)}\n`
  )
  console.info(`Wrote ${OUTPUT_FILE} (${kept} countries, ${failed} failed)`)
}

await main()
