/**
 * Generates data/city-plans/<slug>.gen.ts — the Ground Plan round's tiles —
 * from OpenStreetMap via Overpass (ODbL-1.0).
 *
 * One file per cut, lazy-imported one at a time by the view, because a tile is
 * ~15KB gzipped and a roster is not something to ship whole. Also writes
 * data/city-plans.gen.ts (the roster index, which does ship) and a report
 * naming every tile that failed the coverage floor.
 *
 *   bun run generate:city-plans                the whole roster
 *   bun run generate:city-plans --city london   one city's cuts
 *   bun run generate:city-plans --cached        re-encode, no network
 */
import { mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { jsonParseLiteral } from '../../lib/emit'
import { MINIMUM_STREET_DENSITY } from '../../lib/city-plan-geometry'
import { CITY_CUTS, type CityEntry } from '../../data/city-cuts'
import { buildTile, type CityPlanTile } from './city-plan'
import { overpassQuery, tileQuery } from './overpass'
import type { GroundPlanCity } from '../../../types/challenges/group-modes.type'

type RosterEntry = GroundPlanCity

const OUTPUT_DIRECTORY = 'data/city-plans'
const INDEX_FILE = 'data/city-plans.gen.ts'
const REPORT_FILE = 'generators/data/city-plans-report.txt'
const ATTRIBUTION_FILE = 'lib/attribution.ts'

const only = process.argv.includes('--city')
  ? process.argv[process.argv.indexOf('--city') + 1]
  : undefined
const cacheOnly = process.argv.includes('--cached')

const slugFile = (slug: string) => `${OUTPUT_DIRECTORY}/${slug}.gen.ts`

const writeTile = (slug: string, tile: CityPlanTile, extractedAt: string) => {
  // The measurements stay in the report and the index; the shipped tile is
  // paths only.
  const { crossings: _c, density: _d, vertices: _v, ...paths } = tile
  writeFileSync(
    slugFile(slug),
    `// Generated by generators/vendors/osm/create-city-plans.ts — do not edit by hand.
// Source: OpenStreetMap via Overpass (ODbL-1.0), extracted ${extractedAt}.
// Projected into the tile frame by the generator; see lib/ground-plan.ts.
import type { CityPlanPaths } from '~~/types/challenges/group-modes.type'

export const CITY_PLAN: CityPlanPaths = ${jsonParseLiteral(paths)}
`
  )
}

const run = async () => {
  mkdirSync(OUTPUT_DIRECTORY, { recursive: true })
  const report: string[] = []
  const index: Record<string, { crossings: number }> = {}
  const roster: RosterEntry[] = []
  const wanted = new Set<string>()
  let extractedAt = new Date().toISOString().slice(0, 10)

  const entries: CityEntry[] = only
    ? CITY_CUTS.filter(entry => entry.cuts.some(cut => cut.slug.startsWith(only)))
    : CITY_CUTS

  for (const entry of entries) {
    const dealt: { slug: string; signature: boolean }[] = []
    for (const cut of entry.cuts) {
      if (only && !cut.slug.startsWith(only)) continue
      wanted.add(cut.slug)

      // The tile is cheap to rebuild from the query cache, and rebuilding is
      // what keeps the index's crossing count true — carrying a stale entry
      // forward would have the reveal state a bridge count nobody measured.
      const response = await overpassQuery(tileQuery(cut.box), { label: cut.slug, cacheOnly })
      if (!response) {
        report.push(`${cut.slug.padEnd(28)} NOT FETCHED — no tile written`)
        continue
      }
      if (response.osm3s?.timestamp_osm_base) {
        extractedAt = response.osm3s.timestamp_osm_base.slice(0, 10)
      }

      const tile = buildTile(response, cut.box)

      // A tile nobody mapped is not a question about a city — fail it out of
      // the pool rather than dealing an unfairly empty frame.
      if (tile.density < MINIMUM_STREET_DENSITY) {
        report.push(
          `${cut.slug.padEnd(28)} THIN — ${tile.density.toFixed(1)} km/km² below the ${MINIMUM_STREET_DENSITY} floor`
        )
        continue
      }

      writeTile(cut.slug, tile, extractedAt)
      index[cut.slug] = { crossings: tile.crossings }
      dealt.push({ slug: cut.slug, signature: cut.signature })
      report.push(
        `${cut.slug.padEnd(28)} ${String(tile.vertices).padStart(6)} verts  ` +
          `${tile.density.toFixed(1).padStart(5)} km/km²  ` +
          `${String(tile.crossings).padStart(2)} crossings  ` +
          `${cut.signature ? 'signature' : 'generic'}`
      )
    }

    // A city with no surviving cut cannot be dealt, so it stays off the roster
    // the runtime reads rather than shipping as an entry that deals nothing.
    if (!dealt.length) {
      report.push(`${entry.city.padEnd(28)} DROPPED — no usable cut`)
      continue
    }
    roster.push({
      country: entry.country,
      city: entry.city,
      ...(entry.aliases ? { aliases: entry.aliases } : {}),
      cuts: dealt,
      ...(entry.lesson ? { lesson: entry.lesson } : {}),
      ...(entry.image ? { image: entry.image } : {}),
    })
  }

  // A tile whose cut left the roster would keep its DATASETS claim and fail
  // the attribution suite, so a full run sweeps the directory.
  if (!only) {
    for (const file of readdirSync(OUTPUT_DIRECTORY)) {
      const slug = file.replace(/\.gen\.ts$/, '')
      if (file.endsWith('.gen.ts') && !wanted.has(slug)) {
        unlinkSync(`${OUTPUT_DIRECTORY}/${file}`)
        report.push(`${slug.padEnd(28)} REMOVED — no longer in the roster`)
      }
    }
  }

  writeFileSync(
    INDEX_FILE,
    `// Generated by generators/vendors/osm/create-city-plans.ts — do not edit by hand.
// Source: OpenStreetMap via Overpass (ODbL-1.0), extracted ${extractedAt}.
// The roster index: which tiles exist and what each one's reveal states. The
// tiles themselves are lazy-imported one at a time — see lib/ground-plan.ts.
import type { CityPlanIndexEntry, GroundPlanCity } from '~~/types/challenges/group-modes.type'

export const CITY_PLAN_INDEX: Record<string, CityPlanIndexEntry> = ${jsonParseLiteral(index)}

export const GROUND_PLAN_CITIES: GroundPlanCity[] = ${jsonParseLiteral(roster)}
`
  )

  // DATASETS.files takes literal paths, so the claim is rewritten here rather
  // than hand-maintained: a tile that shipped unclaimed would fail the
  // attribution suite, and one claimed after being dropped fails it too.
  const claim = [INDEX_FILE, ...Object.keys(index).sort().map(slugFile)]
    .map(file => `      '${file}',`)
    .join('\n')
  const attribution = readFileSync(ATTRIBUTION_FILE, 'utf-8')
  writeFileSync(
    ATTRIBUTION_FILE,
    attribution.replace(
      /(\n {2}'city-plans': \{[\s\S]*?files: \[\n)[\s\S]*?(\n {4}\],)/,
      (_match, head: string, tail: string) => `${head}${claim}${tail}`
    )
  )

  writeFileSync(REPORT_FILE, `${report.join('\n')}\n`)
  console.info(report.join('\n'))
  console.info(`\nWrote ${Object.keys(index).length} tiles → ${OUTPUT_DIRECTORY}`)
}

await run()
