import { writeFileSync } from 'fs'
import { join } from 'path'
import { getCountryDataList } from 'countries-list'
import { type ISOCountryCode, isValidISOCode } from '../types/geography.types'
import { parseCSV, columnLookup } from './lib/csv'

const OUTPUT_FILE = 'data/marriage-rights.gen.ts'
const SLUG = 'marriage-same-sex-partners-equaldex'

/**
 * Year same-sex marriage became legal nationwide, from Our World in Data's
 * Equaldex grapher (CC BY 4.0, refreshed annually — last May 2026).
 *
 * The CSV carries a status per country per year since 1950. Only the literal
 * `Legal` counts: `Varies by region` covers early single-state recognition, so
 * treating it as legalization dates the US to 1973 and Mexico to 1950.
 *
 *   bun run generate:marriage-rights
 */

/** Below this the round is too thin to ship — a partial fetch or an Equaldex
 *  schema change must fail the run, not silently shrink the country pool. */
const MARRIAGE_COUNTRY_FLOOR = 35

const LEGAL = 'Legal'

interface MarriageOverride {
  year: number
  note: string
}

/** The two countries where OWID's status year is not the year the game asks
 *  for. Both are deliberate: the notes ship to the reveal, so a reader can see
 *  why the number differs from the source rather than assuming a typo. */
const OVERRIDES: Partial<Record<ISOCountryCode, MarriageOverride>> = {
  // OWID holds the UK at "Varies by region" until Northern Ireland joined in
  // 2020. The round asks for nationwide legality, but 2014 is the answer the
  // question intends and the one players give.
  GB: {
    year: 2014,
    note: 'England, Wales and Scotland from 2014; Northern Ireland followed in 2020.',
  },
  // Equaldex dates Finland to the law's passage in 2014; it took effect on
  // 1 March 2017. The gap is not visible in the CSV.
  FI: {
    year: 2017,
    note: 'Parliament passed the law in 2014; it took effect in 2017.',
  },
}

export interface MarriageRight {
  year: number
  /** Shown at reveal when this country's year needs qualifying. */
  note?: string
}

/** OWID keys by ISO-3; build an ISO-3 -> ISO-2 lookup from countries-list. */
const iso3ToIso2 = (): Map<string, ISOCountryCode> => {
  const map = new Map<string, ISOCountryCode>()
  for (const { iso2, iso3 } of getCountryDataList()) {
    if (iso3 && isValidISOCode(iso2)) map.set(iso3, iso2)
  }
  return map
}

const createMarriageRightsFile = async () => {
  const response = await fetch(`https://ourworldindata.org/grapher/${SLUG}.csv?csvType=full`, {
    headers: { 'User-Agent': 'mondiale-generator' },
  })
  if (!response.ok) throw new Error(`OWID ${SLUG} returned ${response.status}`)

  const rows = parseCSV(await response.text())
  const header = rows.shift()
  if (!header) throw new Error(`OWID ${SLUG} CSV is empty`)

  const column = columnLookup(header, SLUG)
  const codeIndex = column('Code')
  const yearIndex = column('Year')
  const statusIndex = column('Same-sex marriage')

  const lookup = iso3ToIso2()
  const earliest = new Map<ISOCountryCode, number>()
  for (const row of rows) {
    if (row[statusIndex] !== LEGAL) continue
    const isoCode = lookup.get(row[codeIndex])
    if (!isoCode) continue
    const year = Number(row[yearIndex])
    if (!Number.isFinite(year)) continue
    const existing = earliest.get(isoCode)
    if (existing === undefined || year < existing) earliest.set(isoCode, year)
  }

  const rights: Partial<Record<ISOCountryCode, MarriageRight>> = {}
  for (const [isoCode, year] of [...earliest].sort(([a], [b]) => a.localeCompare(b))) {
    const override = OVERRIDES[isoCode]
    rights[isoCode] = override ? { year: override.year, note: override.note } : { year }
  }

  const missingOverrides = Object.keys(OVERRIDES).filter(isoCode => !(isoCode in rights))
  if (missingOverrides.length) {
    throw new Error(
      `Override(s) for ${missingOverrides.join(', ')} no longer match a country in the dataset`
    )
  }

  const count = Object.keys(rights).length
  if (count < MARRIAGE_COUNTRY_FLOOR) {
    throw new Error(
      `Only ${count} countries with same-sex marriage (floor ${MARRIAGE_COUNTRY_FLOOR}) — refusing to write ${OUTPUT_FILE}`
    )
  }

  writeFileSync(
    join(import.meta.dirname, '..', OUTPUT_FILE),
    `// Generated by generators/create-marriage-rights-file.ts — do not edit by hand.
// Source: Equaldex via Our World in Data, "${SLUG}" (CC BY 4.0).
import type { ISOCountryCode } from '~~/types/geography.types'
import type { MarriageRight } from '../generators/create-marriage-rights-file'

export const MARRIAGE_RIGHTS: { [isoCode in ISOCountryCode]?: MarriageRight } = ${JSON.stringify(
      rights,
      null,
      2
    )}
`
  )
  console.info(`Finished creating file: ${OUTPUT_FILE} (${count} countries)`)
}

createMarriageRightsFile()
