import { writeFileSync } from 'fs'
import { join } from 'path'
import { ISOCountryCodes } from '../data/iso-codes.gen'
import type { ISOCountryCode } from '../types/geography.types'

/**
 * Land-border adjacency between the countries in the game's ISO set,
 * authored as one-directional pairs and expanded symmetrically below.
 *
 * Editorial choices (kept close to travle.earth conventions):
 * - France is continental France only (no Brazil/Suriname via French Guiana).
 * - Spain–Morocco counts (Ceuta & Melilla are real land borders).
 * - Morocco–Mauritania counts (Western Sahara is not in the ISO set).
 * - Serbia–Albania does NOT count (they are only adjacent via Kosovo, which
 *   is in the set and carries the RS/AL routes itself).
 * - Bridges/causeways/tunnels do not count (no SG–MY, BH–SA, GB–FR).
 */
const BORDER_PAIRS: [ISOCountryCode, ISOCountryCode][] = [
  // Europe
  ['PT', 'ES'],
  ['ES', 'FR'],
  ['ES', 'AD'],
  ['ES', 'MA'],
  ['AD', 'FR'],
  ['FR', 'BE'],
  ['FR', 'LU'],
  ['FR', 'DE'],
  ['FR', 'CH'],
  ['FR', 'IT'],
  ['FR', 'MC'],
  ['BE', 'LU'],
  ['BE', 'NL'],
  ['BE', 'DE'],
  ['NL', 'DE'],
  ['LU', 'DE'],
  ['DE', 'CH'],
  ['DE', 'AT'],
  ['DE', 'CZ'],
  ['DE', 'PL'],
  ['DE', 'DK'],
  ['CH', 'AT'],
  ['CH', 'IT'],
  ['CH', 'LI'],
  ['LI', 'AT'],
  ['AT', 'IT'],
  ['AT', 'SI'],
  ['AT', 'HU'],
  ['AT', 'SK'],
  ['AT', 'CZ'],
  ['IT', 'SI'],
  ['IT', 'SM'],
  ['IT', 'VA'],
  ['SI', 'HU'],
  ['SI', 'HR'],
  ['HR', 'HU'],
  ['HR', 'RS'],
  ['HR', 'BA'],
  ['HR', 'ME'],
  ['BA', 'RS'],
  ['BA', 'ME'],
  ['ME', 'RS'],
  ['ME', 'AL'],
  ['RS', 'HU'],
  ['RS', 'RO'],
  ['RS', 'BG'],
  ['RS', 'MK'],
  ['XK', 'RS'],
  ['XK', 'AL'],
  ['XK', 'MK'],
  ['XK', 'ME'],
  ['AL', 'MK'],
  ['AL', 'GR'],
  ['MK', 'BG'],
  ['MK', 'GR'],
  ['GR', 'BG'],
  ['GR', 'TR'],
  ['BG', 'RO'],
  ['BG', 'TR'],
  ['RO', 'HU'],
  ['RO', 'UA'],
  ['RO', 'MD'],
  ['MD', 'UA'],
  ['HU', 'SK'],
  ['HU', 'UA'],
  ['SK', 'CZ'],
  ['SK', 'PL'],
  ['SK', 'UA'],
  ['CZ', 'PL'],
  ['PL', 'UA'],
  ['PL', 'BY'],
  ['PL', 'LT'],
  ['PL', 'RU'],
  ['UA', 'BY'],
  ['UA', 'RU'],
  ['BY', 'LT'],
  ['BY', 'LV'],
  ['BY', 'RU'],
  ['LT', 'LV'],
  ['LT', 'RU'],
  ['LV', 'EE'],
  ['LV', 'RU'],
  ['EE', 'RU'],
  ['FI', 'SE'],
  ['FI', 'NO'],
  ['FI', 'RU'],
  ['SE', 'NO'],
  ['NO', 'RU'],
  ['IE', 'GB'],

  // Caucasus & Middle East
  ['RU', 'GE'],
  ['RU', 'AZ'],
  ['RU', 'KZ'],
  ['RU', 'MN'],
  ['RU', 'CN'],
  ['RU', 'KP'],
  ['GE', 'AZ'],
  ['GE', 'AM'],
  ['GE', 'TR'],
  ['AM', 'AZ'],
  ['AM', 'TR'],
  ['AM', 'IR'],
  ['AZ', 'IR'],
  ['AZ', 'TR'],
  ['TR', 'IR'],
  ['TR', 'IQ'],
  ['TR', 'SY'],
  ['SY', 'IQ'],
  ['SY', 'JO'],
  ['SY', 'IL'],
  ['SY', 'LB'],
  ['LB', 'IL'],
  ['IL', 'JO'],
  ['IL', 'EG'],
  ['IL', 'PS'],
  ['PS', 'JO'],
  ['PS', 'EG'],
  ['JO', 'IQ'],
  ['JO', 'SA'],
  ['IQ', 'SA'],
  ['IQ', 'KW'],
  ['IQ', 'IR'],
  ['KW', 'SA'],
  ['SA', 'QA'],
  ['SA', 'AE'],
  ['SA', 'OM'],
  ['SA', 'YE'],
  ['AE', 'OM'],
  ['OM', 'YE'],

  // Central & South Asia
  ['KZ', 'CN'],
  ['KZ', 'KG'],
  ['KZ', 'UZ'],
  ['KZ', 'TM'],
  ['UZ', 'KG'],
  ['UZ', 'TJ'],
  ['UZ', 'AF'],
  ['UZ', 'TM'],
  ['TM', 'AF'],
  ['TM', 'IR'],
  ['KG', 'TJ'],
  ['KG', 'CN'],
  ['TJ', 'AF'],
  ['TJ', 'CN'],
  ['AF', 'IR'],
  ['AF', 'CN'],
  ['AF', 'PK'],
  ['PK', 'IR'],
  ['PK', 'CN'],
  ['PK', 'IN'],
  ['IN', 'CN'],
  ['IN', 'NP'],
  ['IN', 'BT'],
  ['IN', 'BD'],
  ['IN', 'MM'],
  ['NP', 'CN'],
  ['BT', 'CN'],
  ['BD', 'MM'],

  // East & Southeast Asia
  ['CN', 'MN'],
  ['CN', 'MM'],
  ['CN', 'LA'],
  ['CN', 'VN'],
  ['CN', 'KP'],
  ['KP', 'KR'],
  ['MM', 'LA'],
  ['MM', 'TH'],
  ['TH', 'LA'],
  ['TH', 'KH'],
  ['TH', 'MY'],
  ['LA', 'VN'],
  ['LA', 'KH'],
  ['VN', 'KH'],
  ['MY', 'ID'],
  ['MY', 'BN'],
  ['ID', 'PG'],
  ['ID', 'TL'],

  // Africa
  ['MA', 'DZ'],
  ['MA', 'MR'],
  ['DZ', 'TN'],
  ['DZ', 'LY'],
  ['DZ', 'NE'],
  ['DZ', 'ML'],
  ['DZ', 'MR'],
  ['TN', 'LY'],
  ['LY', 'NE'],
  ['LY', 'TD'],
  ['LY', 'SD'],
  ['LY', 'EG'],
  ['EG', 'SD'],
  ['SD', 'TD'],
  ['SD', 'CF'],
  ['SD', 'SS'],
  ['SD', 'ET'],
  ['SD', 'ER'],
  ['SS', 'ET'],
  ['SS', 'KE'],
  ['SS', 'UG'],
  ['SS', 'CD'],
  ['SS', 'CF'],
  ['ER', 'ET'],
  ['ER', 'DJ'],
  ['ET', 'DJ'],
  ['ET', 'SO'],
  ['ET', 'KE'],
  ['DJ', 'SO'],
  ['SO', 'KE'],
  ['KE', 'UG'],
  ['KE', 'TZ'],
  ['UG', 'CD'],
  ['UG', 'RW'],
  ['UG', 'TZ'],
  ['RW', 'CD'],
  ['RW', 'BI'],
  ['RW', 'TZ'],
  ['BI', 'CD'],
  ['BI', 'TZ'],
  ['TZ', 'CD'],
  ['TZ', 'ZM'],
  ['TZ', 'MW'],
  ['TZ', 'MZ'],
  ['MR', 'ML'],
  ['MR', 'SN'],
  ['ML', 'SN'],
  ['ML', 'GN'],
  ['ML', 'CI'],
  ['ML', 'BF'],
  ['ML', 'NE'],
  ['SN', 'GN'],
  ['SN', 'GW'],
  ['SN', 'GM'],
  ['GW', 'GN'],
  ['GN', 'CI'],
  ['GN', 'LR'],
  ['GN', 'SL'],
  ['SL', 'LR'],
  ['LR', 'CI'],
  ['CI', 'BF'],
  ['CI', 'GH'],
  ['GH', 'BF'],
  ['GH', 'TG'],
  ['TG', 'BF'],
  ['TG', 'BJ'],
  ['BJ', 'BF'],
  ['BJ', 'NE'],
  ['BJ', 'NG'],
  ['BF', 'NE'],
  ['NE', 'TD'],
  ['NE', 'NG'],
  ['NG', 'TD'],
  ['NG', 'CM'],
  ['TD', 'CM'],
  ['TD', 'CF'],
  ['CM', 'CF'],
  ['CM', 'CG'],
  ['CM', 'GA'],
  ['CM', 'GQ'],
  ['CF', 'CD'],
  ['CF', 'CG'],
  ['GQ', 'GA'],
  ['GA', 'CG'],
  ['CG', 'CD'],
  ['CG', 'AO'],
  ['CD', 'ZM'],
  ['CD', 'AO'],
  ['AO', 'ZM'],
  ['AO', 'NA'],
  ['ZM', 'MW'],
  ['ZM', 'MZ'],
  ['ZM', 'ZW'],
  ['ZM', 'BW'],
  ['ZM', 'NA'],
  ['MW', 'MZ'],
  ['MZ', 'ZW'],
  ['MZ', 'ZA'],
  ['MZ', 'SZ'],
  ['ZW', 'ZA'],
  ['ZW', 'BW'],
  ['BW', 'NA'],
  ['BW', 'ZA'],
  ['NA', 'ZA'],
  ['ZA', 'SZ'],
  ['ZA', 'LS'],

  // Americas
  ['CA', 'US'],
  ['US', 'MX'],
  ['MX', 'GT'],
  ['MX', 'BZ'],
  ['GT', 'BZ'],
  ['GT', 'SV'],
  ['GT', 'HN'],
  ['SV', 'HN'],
  ['HN', 'NI'],
  ['NI', 'CR'],
  ['CR', 'PA'],
  ['PA', 'CO'],
  ['CO', 'VE'],
  ['CO', 'EC'],
  ['CO', 'PE'],
  ['CO', 'BR'],
  ['VE', 'GY'],
  ['VE', 'BR'],
  ['GY', 'SR'],
  ['GY', 'BR'],
  ['SR', 'BR'],
  ['EC', 'PE'],
  ['PE', 'BR'],
  ['PE', 'BO'],
  ['PE', 'CL'],
  ['BR', 'BO'],
  ['BR', 'PY'],
  ['BR', 'AR'],
  ['BR', 'UY'],
  ['BO', 'PY'],
  ['BO', 'AR'],
  ['BO', 'CL'],
  ['PY', 'AR'],
  ['CL', 'AR'],
  ['AR', 'UY'],
  ['HT', 'DO'],
]

const validCodes = new Set<string>(ISOCountryCodes)
const borders: { [isoCode: string]: ISOCountryCode[] } = {}
for (const isoCode of ISOCountryCodes) {
  borders[isoCode] = []
}

const seen = new Set<string>()
for (const [a, b] of BORDER_PAIRS) {
  if (!validCodes.has(a) || !validCodes.has(b)) {
    throw new EvalError(`Border pair references unknown ISO code: ${a}-${b}`)
  }
  if (a === b) {
    throw new EvalError(`Self-border: ${a}`)
  }

  const key = [a, b].sort().join('-')
  if (seen.has(key)) {
    throw new EvalError(`Duplicate border pair: ${key}`)
  }
  seen.add(key)

  borders[a].push(b)
  borders[b].push(a)
}

for (const isoCode of ISOCountryCodes) {
  borders[isoCode].sort()
}

const landlocked = ISOCountryCodes.filter(isoCode => borders[isoCode].length === 0)
console.log(`${BORDER_PAIRS.length} border pairs across ${ISOCountryCodes.length} countries`)
console.log(`${landlocked.length} countries without land borders (islands):`, landlocked.join(' '))

const output = `// Generated by generators/create-borders-file.ts — do not edit by hand.
// Land-border adjacency between the game's countries (symmetric).
import type { ISOCountryCode } from '~~/types/geography.types'

export const BORDERS: { [isoCode in ISOCountryCode]: ISOCountryCode[] } = ${JSON.stringify(
  borders,
  null,
  2
)}
`

writeFileSync(join(import.meta.dirname, '../data/borders.gen.ts'), output)
console.log('Wrote data/borders.gen.ts')
