import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ISOCountryCodes } from '../data/iso-codes.gen'

/**
 * The inline flag SVGs, split out of countries.gen: they are 52% of that
 * file's bytes and only two components ever read them (CountryFlag,
 * FlagSketch), while COUNTRIES rides in every challenge dealer and both
 * server bundle graphs. Loaded lazily through lib/country.ts (loadFlags),
 * the same pattern as flags-wide.
 *
 * Reads the same data/static/flags/*.svg the countries generator uses for
 * national colours — regenerate alongside `bun run generate:countries`.
 *
 *   bun run generate:flags
 */

const flags: { [isoCode: string]: string } = {}
for (const isoCode of ISOCountryCodes) {
  flags[isoCode] = readFileSync(
    join(import.meta.dirname, `../data/static/flags/${isoCode.toLowerCase()}.svg`)
  ).toString()
}

const output = `// Generated by generators/create-flags-file.ts — do not edit by hand.
// Inline flag SVG markup (flag-icons), lazy-loaded via lib/country.ts.
import type { ISOCountryCode } from '~~/types/geography.types'

export const FLAGS: { [key in ISOCountryCode]: string } = ${JSON.stringify(flags)}
`
writeFileSync(join(import.meta.dirname, '../data/flags.gen.ts'), output)
console.log(`Wrote data/flags.gen.ts (${ISOCountryCodes.length} flags)`)
