import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { WATER_FEATURES } from '../data/water.gen'
import type { ISOCountryCode } from '../types/geography.types'

/**
 * Manhunt's sea-lane graph: two countries are sea neighbours when their
 * coasts share a named sea (data/water.gen). Precomputed here because the
 * only runtime consumer (lib/manhunt.ts) needs a few KB of adjacency, and a
 * static import of water.gen would drag 1.6 MB of projected geometry into
 * the eager server bundle — defeating every lazy import of that file.
 *
 * Derived data: regenerate after `bun run generate:water`.
 *
 *   bun run generate:sea-lanes
 */

const neighbours = new Map<ISOCountryCode, Set<ISOCountryCode>>()
for (const feature of Object.values(WATER_FEATURES)) {
  if (feature.kind !== 'sea') continue
  for (const shore of feature.countries) {
    const set = neighbours.get(shore) ?? new Set<ISOCountryCode>()
    for (const other of feature.countries) if (other !== shore) set.add(other)
    neighbours.set(shore, set)
  }
}

const seaLanes: { [isoCode: string]: ISOCountryCode[] } = {}
for (const [isoCode, set] of [...neighbours].sort(([a], [b]) => a.localeCompare(b))) {
  seaLanes[isoCode] = [...set].sort()
}

const output = `// Generated by generators/create-sea-lanes-file.ts — do not edit by hand.
// Sea adjacency by shared named sea (data/water.gen); manhunt's sea-lane graph.
import type { ISOCountryCode } from '~~/types/geography.types'

export const SEA_NEIGHBOURS: Partial<Record<ISOCountryCode, ISOCountryCode[]>> = ${JSON.stringify(
  seaLanes,
  null,
  2
)}
`
writeFileSync(join(import.meta.dirname, '../data/sea-lanes.gen.ts'), output)
console.log('Wrote data/sea-lanes.gen.ts')
