// Generated by generators/create-borders-file.ts — do not edit by hand.
// Land-border adjacency between the game's countries (symmetric).
import type { ISOCountryCode } from '~~/types/geography.types'

export const BORDERS: { [isoCode in ISOCountryCode]: ISOCountryCode[] } = {
  "AF": [
    "CN",
    "IR",
    "PK",
    "TJ",
    "TM",
    "UZ"
  ],
  "AL": [
    "GR",
    "ME",
    "MK",
    "XK"
  ],
  "AD": [
    "ES",
    "FR"
  ],
  "AO": [
    "CD",
    "CG",
    "NA",
    "ZM"
  ],
  "AG": [],
  "AR": [
    "BO",
    "BR",
    "CL",
    "PY",
    "UY"
  ],
  "AM": [
    "AZ",
    "GE",
    "IR",
    "TR"
  ],
  "AU": [],
  "AT": [
    "CH",
    "CZ",
    "DE",
    "HU",
    "IT",
    "LI",
    "SI",
    "SK"
  ],
  "AZ": [
    "AM",
    "GE",
    "IR",
    "RU",
    "TR"
  ],
  "BS": [],
  "BH": [],
  "BD": [
    "IN",
    "MM"
  ],
  "BB": [],
  "BY": [
    "LT",
    "LV",
    "PL",
    "RU",
    "UA"
  ],
  "BE": [
    "DE",
    "FR",
    "LU",
    "NL"
  ],
  "BZ": [
    "GT",
    "MX"
  ],
  "BJ": [
    "BF",
    "NE",
    "NG",
    "TG"
  ],
  "BT": [
    "CN",
    "IN"
  ],
  "BO": [
    "AR",
    "BR",
    "CL",
    "PE",
    "PY"
  ],
  "BA": [
    "HR",
    "ME",
    "RS"
  ],
  "BW": [
    "NA",
    "ZA",
    "ZM",
    "ZW"
  ],
  "BR": [
    "AR",
    "BO",
    "CO",
    "GY",
    "PE",
    "PY",
    "SR",
    "UY",
    "VE"
  ],
  "BN": [
    "MY"
  ],
  "BG": [
    "GR",
    "MK",
    "RO",
    "RS",
    "TR"
  ],
  "BF": [
    "BJ",
    "CI",
    "GH",
    "ML",
    "NE",
    "TG"
  ],
  "BI": [
    "CD",
    "RW",
    "TZ"
  ],
  "KH": [
    "LA",
    "TH",
    "VN"
  ],
  "CM": [
    "CF",
    "CG",
    "GA",
    "GQ",
    "NG",
    "TD"
  ],
  "CA": [
    "US"
  ],
  "CV": [],
  "CF": [
    "CD",
    "CG",
    "CM",
    "SD",
    "SS",
    "TD"
  ],
  "TD": [
    "CF",
    "CM",
    "LY",
    "NE",
    "NG",
    "SD"
  ],
  "CL": [
    "AR",
    "BO",
    "PE"
  ],
  "CN": [
    "AF",
    "BT",
    "HK",
    "IN",
    "KG",
    "KP",
    "KZ",
    "LA",
    "MM",
    "MN",
    "NP",
    "PK",
    "RU",
    "TJ",
    "VN"
  ],
  "CO": [
    "BR",
    "EC",
    "PA",
    "PE",
    "VE"
  ],
  "KM": [],
  "CG": [
    "AO",
    "CD",
    "CF",
    "CM",
    "GA"
  ],
  "CD": [
    "AO",
    "BI",
    "CF",
    "CG",
    "RW",
    "SS",
    "TZ",
    "UG",
    "ZM"
  ],
  "CR": [
    "NI",
    "PA"
  ],
  "CI": [
    "BF",
    "GH",
    "GN",
    "LR",
    "ML"
  ],
  "HR": [
    "BA",
    "HU",
    "ME",
    "RS",
    "SI"
  ],
  "CU": [],
  "CY": [],
  "CZ": [
    "AT",
    "DE",
    "PL",
    "SK"
  ],
  "DK": [
    "DE"
  ],
  "DJ": [
    "ER",
    "ET",
    "SO"
  ],
  "DM": [],
  "DO": [
    "HT"
  ],
  "DZ": [
    "LY",
    "MA",
    "ML",
    "MR",
    "NE",
    "TN"
  ],
  "EC": [
    "CO",
    "PE"
  ],
  "EG": [
    "IL",
    "LY",
    "PS",
    "SD"
  ],
  "SV": [
    "GT",
    "HN"
  ],
  "GQ": [
    "CM",
    "GA"
  ],
  "ER": [
    "DJ",
    "ET",
    "SD"
  ],
  "EE": [
    "LV",
    "RU"
  ],
  "ET": [
    "DJ",
    "ER",
    "KE",
    "SD",
    "SO",
    "SS"
  ],
  "FJ": [],
  "FI": [
    "NO",
    "RU",
    "SE"
  ],
  "FR": [
    "AD",
    "BE",
    "CH",
    "DE",
    "ES",
    "IT",
    "LU",
    "MC"
  ],
  "GA": [
    "CG",
    "CM",
    "GQ"
  ],
  "GM": [
    "SN"
  ],
  "GE": [
    "AM",
    "AZ",
    "RU",
    "TR"
  ],
  "DE": [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DK",
    "FR",
    "LU",
    "NL",
    "PL"
  ],
  "GH": [
    "BF",
    "CI",
    "TG"
  ],
  "GR": [
    "AL",
    "BG",
    "MK",
    "TR"
  ],
  "GD": [],
  "GT": [
    "BZ",
    "HN",
    "MX",
    "SV"
  ],
  "GN": [
    "CI",
    "GW",
    "LR",
    "ML",
    "SL",
    "SN"
  ],
  "GW": [
    "GN",
    "SN"
  ],
  "GY": [
    "BR",
    "SR",
    "VE"
  ],
  "HT": [
    "DO"
  ],
  "VA": [
    "IT"
  ],
  "HN": [
    "GT",
    "NI",
    "SV"
  ],
  "HK": [
    "CN"
  ],
  "HU": [
    "AT",
    "HR",
    "RO",
    "RS",
    "SI",
    "SK",
    "UA"
  ],
  "IS": [],
  "IN": [
    "BD",
    "BT",
    "CN",
    "MM",
    "NP",
    "PK"
  ],
  "ID": [
    "MY",
    "PG",
    "TL"
  ],
  "IR": [
    "AF",
    "AM",
    "AZ",
    "IQ",
    "PK",
    "TM",
    "TR"
  ],
  "IQ": [
    "IR",
    "JO",
    "KW",
    "SA",
    "SY",
    "TR"
  ],
  "IE": [
    "GB"
  ],
  "IL": [
    "EG",
    "JO",
    "LB",
    "PS",
    "SY"
  ],
  "IT": [
    "AT",
    "CH",
    "FR",
    "SI",
    "SM",
    "VA"
  ],
  "JM": [],
  "JP": [],
  "JO": [
    "IL",
    "IQ",
    "PS",
    "SA",
    "SY"
  ],
  "KZ": [
    "CN",
    "KG",
    "RU",
    "TM",
    "UZ"
  ],
  "KE": [
    "ET",
    "SO",
    "SS",
    "TZ",
    "UG"
  ],
  "KI": [],
  "KR": [
    "KP"
  ],
  "KP": [
    "CN",
    "KR",
    "RU"
  ],
  "KW": [
    "IQ",
    "SA"
  ],
  "KG": [
    "CN",
    "KZ",
    "TJ",
    "UZ"
  ],
  "LA": [
    "CN",
    "KH",
    "MM",
    "TH",
    "VN"
  ],
  "LV": [
    "BY",
    "EE",
    "LT",
    "RU"
  ],
  "LB": [
    "IL",
    "SY"
  ],
  "LS": [
    "ZA"
  ],
  "LR": [
    "CI",
    "GN",
    "SL"
  ],
  "LY": [
    "DZ",
    "EG",
    "NE",
    "SD",
    "TD",
    "TN"
  ],
  "LI": [
    "AT",
    "CH"
  ],
  "LT": [
    "BY",
    "LV",
    "PL",
    "RU"
  ],
  "LU": [
    "BE",
    "DE",
    "FR"
  ],
  "MG": [],
  "MW": [
    "MZ",
    "TZ",
    "ZM"
  ],
  "MY": [
    "BN",
    "ID",
    "TH"
  ],
  "MV": [],
  "ML": [
    "BF",
    "CI",
    "DZ",
    "GN",
    "MR",
    "NE",
    "SN"
  ],
  "MT": [],
  "MR": [
    "DZ",
    "MA",
    "ML",
    "SN"
  ],
  "MU": [],
  "MX": [
    "BZ",
    "GT",
    "US"
  ],
  "FM": [],
  "MD": [
    "RO",
    "UA"
  ],
  "MC": [
    "FR"
  ],
  "MN": [
    "CN",
    "RU"
  ],
  "ME": [
    "AL",
    "BA",
    "HR",
    "RS",
    "XK"
  ],
  "MA": [
    "DZ",
    "ES",
    "MR"
  ],
  "MZ": [
    "MW",
    "SZ",
    "TZ",
    "ZA",
    "ZM",
    "ZW"
  ],
  "MM": [
    "BD",
    "CN",
    "IN",
    "LA",
    "TH"
  ],
  "NA": [
    "AO",
    "BW",
    "ZA",
    "ZM"
  ],
  "NR": [],
  "NP": [
    "CN",
    "IN"
  ],
  "NL": [
    "BE",
    "DE"
  ],
  "NZ": [],
  "NI": [
    "CR",
    "HN"
  ],
  "NE": [
    "BF",
    "BJ",
    "DZ",
    "LY",
    "ML",
    "NG",
    "TD"
  ],
  "NG": [
    "BJ",
    "CM",
    "NE",
    "TD"
  ],
  "NO": [
    "FI",
    "RU",
    "SE"
  ],
  "OM": [
    "AE",
    "SA",
    "YE"
  ],
  "PK": [
    "AF",
    "CN",
    "IN",
    "IR"
  ],
  "PW": [],
  "PS": [
    "EG",
    "IL",
    "JO"
  ],
  "PA": [
    "CO",
    "CR"
  ],
  "PG": [
    "ID"
  ],
  "PY": [
    "AR",
    "BO",
    "BR"
  ],
  "PE": [
    "BO",
    "BR",
    "CL",
    "CO",
    "EC"
  ],
  "PH": [],
  "PL": [
    "BY",
    "CZ",
    "DE",
    "LT",
    "RU",
    "SK",
    "UA"
  ],
  "PT": [
    "ES"
  ],
  "QA": [
    "SA"
  ],
  "MK": [
    "AL",
    "BG",
    "GR",
    "RS",
    "XK"
  ],
  "RO": [
    "BG",
    "HU",
    "MD",
    "RS",
    "UA"
  ],
  "RU": [
    "AZ",
    "BY",
    "CN",
    "EE",
    "FI",
    "GE",
    "KP",
    "KZ",
    "LT",
    "LV",
    "MN",
    "NO",
    "PL",
    "UA"
  ],
  "RW": [
    "BI",
    "CD",
    "TZ",
    "UG"
  ],
  "KN": [],
  "LC": [],
  "SM": [
    "IT"
  ],
  "ST": [],
  "SA": [
    "AE",
    "IQ",
    "JO",
    "KW",
    "OM",
    "QA",
    "YE"
  ],
  "SN": [
    "GM",
    "GN",
    "GW",
    "ML",
    "MR"
  ],
  "RS": [
    "BA",
    "BG",
    "HR",
    "HU",
    "ME",
    "MK",
    "RO",
    "XK"
  ],
  "SC": [],
  "SL": [
    "GN",
    "LR"
  ],
  "SG": [],
  "SK": [
    "AT",
    "CZ",
    "HU",
    "PL",
    "UA"
  ],
  "SI": [
    "AT",
    "HR",
    "HU",
    "IT"
  ],
  "SB": [],
  "SO": [
    "DJ",
    "ET",
    "KE"
  ],
  "ZA": [
    "BW",
    "LS",
    "MZ",
    "NA",
    "SZ",
    "ZW"
  ],
  "ES": [
    "AD",
    "FR",
    "MA",
    "PT"
  ],
  "LK": [],
  "SD": [
    "CF",
    "EG",
    "ER",
    "ET",
    "LY",
    "SS",
    "TD"
  ],
  "SS": [
    "CD",
    "CF",
    "ET",
    "KE",
    "SD",
    "UG"
  ],
  "SR": [
    "BR",
    "GY"
  ],
  "SZ": [
    "MZ",
    "ZA"
  ],
  "SE": [
    "FI",
    "NO"
  ],
  "CH": [
    "AT",
    "DE",
    "FR",
    "IT",
    "LI"
  ],
  "SY": [
    "IL",
    "IQ",
    "JO",
    "LB",
    "TR"
  ],
  "TW": [],
  "TJ": [
    "AF",
    "CN",
    "KG",
    "UZ"
  ],
  "TZ": [
    "BI",
    "CD",
    "KE",
    "MW",
    "MZ",
    "RW",
    "UG",
    "ZM"
  ],
  "TH": [
    "KH",
    "LA",
    "MM",
    "MY"
  ],
  "TL": [
    "ID"
  ],
  "TG": [
    "BF",
    "BJ",
    "GH"
  ],
  "TO": [],
  "TT": [],
  "TN": [
    "DZ",
    "LY"
  ],
  "TR": [
    "AM",
    "AZ",
    "BG",
    "GE",
    "GR",
    "IQ",
    "IR",
    "SY"
  ],
  "TM": [
    "AF",
    "IR",
    "KZ",
    "UZ"
  ],
  "TV": [],
  "UG": [
    "CD",
    "KE",
    "RW",
    "SS",
    "TZ"
  ],
  "UA": [
    "BY",
    "HU",
    "MD",
    "PL",
    "RO",
    "RU",
    "SK"
  ],
  "AE": [
    "OM",
    "SA"
  ],
  "GB": [
    "IE"
  ],
  "US": [
    "CA",
    "MX"
  ],
  "UY": [
    "AR",
    "BR"
  ],
  "UZ": [
    "AF",
    "KG",
    "KZ",
    "TJ",
    "TM"
  ],
  "VU": [],
  "VE": [
    "BR",
    "CO",
    "GY"
  ],
  "VN": [
    "CN",
    "KH",
    "LA"
  ],
  "YE": [
    "OM",
    "SA"
  ],
  "ZM": [
    "AO",
    "BW",
    "CD",
    "MW",
    "MZ",
    "NA",
    "TZ",
    "ZW"
  ],
  "ZW": [
    "BW",
    "MZ",
    "ZA",
    "ZM"
  ],
  "XK": [
    "AL",
    "ME",
    "MK",
    "RS"
  ]
}
