// Generated by generators/create-marriage-rights-file.ts — do not edit by hand.
// Source: Equaldex via Our World in Data, "marriage-same-sex-partners-equaldex" (CC BY 4.0).
import type { ISOCountryCode } from '~~/types/geography.types'
import type { MarriageRight } from '../generators/create-marriage-rights-file'

export const MARRIAGE_RIGHTS: { [isoCode in ISOCountryCode]?: MarriageRight } = {
  "AD": {
    "year": 2023
  },
  "AR": {
    "year": 2010
  },
  "AT": {
    "year": 2019
  },
  "AU": {
    "year": 2017
  },
  "BE": {
    "year": 2003
  },
  "BR": {
    "year": 2013
  },
  "CA": {
    "year": 2005
  },
  "CH": {
    "year": 2022
  },
  "CL": {
    "year": 2022
  },
  "CO": {
    "year": 2016
  },
  "CR": {
    "year": 2020
  },
  "CU": {
    "year": 2022
  },
  "DE": {
    "year": 2017
  },
  "DK": {
    "year": 2012
  },
  "EC": {
    "year": 2019
  },
  "EE": {
    "year": 2024
  },
  "ES": {
    "year": 2005
  },
  "FI": {
    "year": 2017,
    "note": "Parliament passed the law in 2014; it took effect in 2017."
  },
  "FR": {
    "year": 2013
  },
  "GB": {
    "year": 2014,
    "note": "England, Wales and Scotland from 2014; Northern Ireland followed in 2020."
  },
  "GR": {
    "year": 2024
  },
  "IE": {
    "year": 2015
  },
  "IS": {
    "year": 2010
  },
  "LI": {
    "year": 2025
  },
  "LU": {
    "year": 2015
  },
  "MT": {
    "year": 2017
  },
  "MX": {
    "year": 2022
  },
  "NL": {
    "year": 2001
  },
  "NO": {
    "year": 2009
  },
  "NZ": {
    "year": 2013
  },
  "PT": {
    "year": 2010
  },
  "SE": {
    "year": 2009
  },
  "SI": {
    "year": 2022
  },
  "TH": {
    "year": 2025
  },
  "TW": {
    "year": 2019
  },
  "US": {
    "year": 2015
  },
  "UY": {
    "year": 2013
  },
  "ZA": {
    "year": 2006
  }
}
