// Generated by generators/create-straits-file.ts — do not edit by hand.
// Sea adjacency (coastlines within 150 km across own waters, symmetric).
// Border Chain only — deliberately separate from BORDERS.
import type { ISOCountryCode } from '~~/types/geography.types'

export const STRAITS: { [isoCode in ISOCountryCode]: ISOCountryCode[] } = {
  "AF": [],
  "AL": [
    "IT"
  ],
  "AD": [],
  "AO": [],
  "AG": [
    "KN"
  ],
  "AR": [],
  "AM": [],
  "AU": [
    "ID",
    "PG"
  ],
  "AT": [],
  "AZ": [],
  "BS": [
    "CU",
    "HT",
    "US"
  ],
  "BH": [
    "QA",
    "SA"
  ],
  "BD": [],
  "BB": [
    "LC"
  ],
  "BY": [],
  "BE": [],
  "BZ": [
    "HN"
  ],
  "BJ": [],
  "BT": [],
  "BO": [],
  "BA": [],
  "BW": [],
  "BR": [],
  "BN": [],
  "BG": [],
  "BF": [],
  "BI": [],
  "KH": [],
  "CM": [],
  "CA": [],
  "CV": [],
  "CF": [],
  "TD": [],
  "CL": [],
  "CN": [
    "TW"
  ],
  "CO": [
    "NI"
  ],
  "KM": [],
  "CG": [],
  "CD": [],
  "CR": [],
  "CI": [],
  "HR": [
    "IT"
  ],
  "CU": [
    "BS",
    "HT",
    "JM"
  ],
  "CY": [
    "SY",
    "TR"
  ],
  "CZ": [],
  "DK": [
    "NO",
    "PL",
    "SE"
  ],
  "DJ": [
    "YE"
  ],
  "DM": [
    "LC"
  ],
  "DO": [],
  "DZ": [],
  "EC": [],
  "EG": [
    "JO",
    "SA"
  ],
  "SV": [
    "NI"
  ],
  "GQ": [],
  "ER": [
    "YE"
  ],
  "EE": [
    "FI",
    "SE"
  ],
  "ET": [],
  "FJ": [],
  "FI": [
    "EE"
  ],
  "FR": [
    "GB"
  ],
  "GA": [],
  "GM": [],
  "GE": [],
  "DE": [
    "SE"
  ],
  "GH": [],
  "GR": [
    "IT"
  ],
  "GD": [
    "LC",
    "TT",
    "VE"
  ],
  "GT": [],
  "GN": [],
  "GW": [],
  "GY": [],
  "HT": [
    "BS",
    "CU"
  ],
  "VA": [],
  "HN": [
    "BZ"
  ],
  "HU": [],
  "IS": [],
  "IN": [
    "LK",
    "MV"
  ],
  "ID": [
    "AU",
    "PH",
    "SG"
  ],
  "IR": [
    "AE",
    "OM"
  ],
  "IQ": [],
  "IE": [],
  "IL": [],
  "IT": [
    "AL",
    "GR",
    "HR",
    "MT",
    "TN"
  ],
  "JM": [
    "CU"
  ],
  "JP": [
    "KR",
    "RU",
    "TW"
  ],
  "JO": [
    "EG"
  ],
  "KZ": [],
  "KE": [],
  "KI": [],
  "KR": [
    "JP"
  ],
  "KP": [],
  "KW": [],
  "KG": [],
  "LA": [],
  "LV": [
    "SE"
  ],
  "LB": [],
  "LS": [],
  "LR": [],
  "LY": [],
  "LI": [],
  "LT": [],
  "LU": [],
  "MG": [],
  "MW": [],
  "MY": [
    "PH",
    "SG"
  ],
  "MV": [
    "IN"
  ],
  "ML": [],
  "MT": [
    "IT"
  ],
  "MR": [],
  "MU": [],
  "MX": [],
  "FM": [],
  "MD": [],
  "MC": [],
  "MN": [],
  "ME": [],
  "MA": [],
  "MZ": [],
  "MM": [],
  "NA": [],
  "NR": [],
  "NP": [],
  "NL": [],
  "NZ": [],
  "NI": [
    "CO",
    "SV"
  ],
  "NE": [],
  "NG": [],
  "NO": [
    "DK"
  ],
  "OM": [
    "IR"
  ],
  "PK": [],
  "PW": [],
  "PS": [],
  "PA": [],
  "PG": [
    "AU",
    "SB"
  ],
  "PY": [],
  "PE": [],
  "PH": [
    "ID",
    "MY",
    "TW"
  ],
  "PL": [
    "DK"
  ],
  "PT": [],
  "QA": [
    "BH"
  ],
  "MK": [],
  "RO": [],
  "RU": [
    "JP",
    "US"
  ],
  "RW": [],
  "KN": [
    "AG"
  ],
  "LC": [
    "BB",
    "DM",
    "GD"
  ],
  "SM": [],
  "ST": [],
  "SA": [
    "BH",
    "EG"
  ],
  "SN": [],
  "RS": [],
  "SC": [],
  "SL": [],
  "SG": [
    "ID",
    "MY"
  ],
  "SK": [],
  "SI": [],
  "SB": [
    "PG"
  ],
  "SO": [
    "YE"
  ],
  "ZA": [],
  "ES": [],
  "LK": [
    "IN"
  ],
  "SD": [],
  "SS": [],
  "SR": [],
  "SZ": [],
  "SE": [
    "DE",
    "DK",
    "EE",
    "LV"
  ],
  "CH": [],
  "SY": [
    "CY"
  ],
  "TW": [
    "CN",
    "JP",
    "PH"
  ],
  "TJ": [],
  "TZ": [],
  "TH": [],
  "TL": [],
  "TG": [],
  "TO": [],
  "TT": [
    "GD",
    "VE"
  ],
  "TN": [
    "IT"
  ],
  "TR": [
    "CY"
  ],
  "TM": [],
  "TV": [],
  "UG": [],
  "UA": [],
  "AE": [
    "IR"
  ],
  "GB": [
    "FR"
  ],
  "US": [
    "BS",
    "RU"
  ],
  "UY": [],
  "UZ": [],
  "VU": [],
  "VE": [
    "GD",
    "TT"
  ],
  "VN": [],
  "YE": [
    "DJ",
    "ER",
    "SO"
  ],
  "ZM": [],
  "ZW": [],
  "XK": []
}

/** Where each strait is actually crossed (nearest validated coastline points),
 *  keyed by the sorted "A-B" pair — the map draws its sea-hop arcs here. */
export const STRAIT_CROSSINGS: {
  [pair: string]: { from: { lat: number; lng: number }; to: { lat: number; lng: number } }
} = {
  "BH-QA": {
    "from": {
      "lat": 25.6318,
      "lng": 50.8116
    },
    "to": {
      "lat": 25.6206,
      "lng": 50.8096
    }
  },
  "MY-SG": {
    "from": {
      "lat": 1.4537,
      "lng": 103.7741
    },
    "to": {
      "lat": 1.4443,
      "lng": 103.79
    }
  },
  "RU-US": {
    "from": {
      "lat": 65.7739,
      "lng": -169.0275
    },
    "to": {
      "lat": 65.7647,
      "lng": -168.943
    }
  },
  "DK-SE": {
    "from": {
      "lat": 56.0438,
      "lng": 12.6219
    },
    "to": {
      "lat": 56.0515,
      "lng": 12.698
    }
  },
  "AU-PG": {
    "from": {
      "lat": -9.3743,
      "lng": 142.6648
    },
    "to": {
      "lat": -9.3303,
      "lng": 142.6526
    }
  },
  "EG-SA": {
    "from": {
      "lat": 27.9721,
      "lng": 34.5749
    },
    "to": {
      "lat": 28.0302,
      "lng": 34.613
    }
  },
  "CN-TW": {
    "from": {
      "lat": 24.5902,
      "lng": 118.3799
    },
    "to": {
      "lat": 24.5227,
      "lng": 118.3942
    }
  },
  "EG-JO": {
    "from": {
      "lat": 29.4901,
      "lng": 34.8867
    },
    "to": {
      "lat": 29.477,
      "lng": 34.9761
    }
  },
  "PG-SB": {
    "from": {
      "lat": -6.8728,
      "lng": 155.7178
    },
    "to": {
      "lat": -6.9661,
      "lng": 155.7349
    }
  },
  "NI-SV": {
    "from": {
      "lat": 13.1679,
      "lng": -87.6932
    },
    "to": {
      "lat": 13.0847,
      "lng": -87.5839
    }
  },
  "TT-VE": {
    "from": {
      "lat": 9.9574,
      "lng": -62.0254
    },
    "to": {
      "lat": 10.0565,
      "lng": -61.9287
    }
  },
  "ID-SG": {
    "from": {
      "lat": 1.3181,
      "lng": 103.9544
    },
    "to": {
      "lat": 1.1879,
      "lng": 104.0309
    }
  },
  "BH-SA": {
    "from": {
      "lat": 26.1597,
      "lng": 50.3827
    },
    "to": {
      "lat": 26.1913,
      "lng": 50.2123
    }
  },
  "JP-RU": {
    "from": {
      "lat": 43.5933,
      "lng": 145.3115
    },
    "to": {
      "lat": 43.7245,
      "lng": 145.4431
    }
  },
  "DJ-YE": {
    "from": {
      "lat": 12.4888,
      "lng": 43.3294
    },
    "to": {
      "lat": 12.6498,
      "lng": 43.3998
    }
  },
  "IN-LK": {
    "from": {
      "lat": 9.159,
      "lng": 79.4536
    },
    "to": {
      "lat": 9.0896,
      "lng": 79.698
    }
  },
  "AG-KN": {
    "from": {
      "lat": 16.9404,
      "lng": -62.3446
    },
    "to": {
      "lat": 17.1089,
      "lng": -62.5436
    }
  },
  "FR-GB": {
    "from": {
      "lat": 50.881,
      "lng": 1.6048
    },
    "to": {
      "lat": 51.131,
      "lng": 1.3572
    }
  },
  "MY-PH": {
    "from": {
      "lat": 5.1286,
      "lng": 119.1956
    },
    "to": {
      "lat": 4.9028,
      "lng": 119.4354
    }
  },
  "ER-YE": {
    "from": {
      "lat": 12.8933,
      "lng": 42.9959
    },
    "to": {
      "lat": 13.0626,
      "lng": 43.3418
    }
  },
  "EE-FI": {
    "from": {
      "lat": 59.5981,
      "lng": 24.5159
    },
    "to": {
      "lat": 59.9923,
      "lng": 24.4456
    }
  },
  "IR-OM": {
    "from": {
      "lat": 26.8276,
      "lng": 56.341
    },
    "to": {
      "lat": 26.386,
      "lng": 56.3638
    }
  },
  "JP-KR": {
    "from": {
      "lat": 34.6951,
      "lng": 129.4233
    },
    "to": {
      "lat": 35.1008,
      "lng": 129.1235
    }
  },
  "AE-IR": {
    "from": {
      "lat": 25.8646,
      "lng": 55.0544
    },
    "to": {
      "lat": 25.5624,
      "lng": 55.5357
    }
  },
  "BS-CU": {
    "from": {
      "lat": 23.494,
      "lng": -79.5176
    },
    "to": {
      "lat": 22.9647,
      "lng": -79.8263
    }
  },
  "IT-TN": {
    "from": {
      "lat": 36.8284,
      "lng": 11.9222
    },
    "to": {
      "lat": 36.8705,
      "lng": 11.1362
    }
  },
  "CY-TR": {
    "from": {
      "lat": 35.3978,
      "lng": 32.9204
    },
    "to": {
      "lat": 36.0272,
      "lng": 32.8037
    }
  },
  "AL-IT": {
    "from": {
      "lat": 40.4204,
      "lng": 19.2896
    },
    "to": {
      "lat": 40.1392,
      "lng": 18.5161
    }
  },
  "DE-SE": {
    "from": {
      "lat": 54.6882,
      "lng": 13.3908
    },
    "to": {
      "lat": 55.3427,
      "lng": 13.3125
    }
  },
  "IT-MT": {
    "from": {
      "lat": 36.726,
      "lng": 14.6846
    },
    "to": {
      "lat": 36.0679,
      "lng": 14.2826
    }
  },
  "BS-US": {
    "from": {
      "lat": 25.7753,
      "lng": -80.1288
    },
    "to": {
      "lat": 25.7023,
      "lng": -79.3043
    }
  },
  "CU-HT": {
    "from": {
      "lat": 19.821,
      "lng": -73.4203
    },
    "to": {
      "lat": 20.1826,
      "lng": -74.142
    }
  },
  "ID-PH": {
    "from": {
      "lat": 5.5654,
      "lng": 126.5986
    },
    "to": {
      "lat": 6.2832,
      "lng": 126.2002
    }
  },
  "SO-YE": {
    "from": {
      "lat": 11.8331,
      "lng": 51.2927
    },
    "to": {
      "lat": 12.222,
      "lng": 52.0685
    }
  },
  "DK-PL": {
    "from": {
      "lat": 54.9916,
      "lng": 15.0727
    },
    "to": {
      "lat": 54.1671,
      "lng": 15.4685
    }
  },
  "BS-HT": {
    "from": {
      "lat": 20.9525,
      "lng": -73.2256
    },
    "to": {
      "lat": 20.082,
      "lng": -72.9011
    }
  },
  "GR-IT": {
    "from": {
      "lat": 39.7482,
      "lng": 19.6265
    },
    "to": {
      "lat": 40.1045,
      "lng": 18.5161
    }
  },
  "CY-SY": {
    "from": {
      "lat": 35.692,
      "lng": 34.5925
    },
    "to": {
      "lat": 35.5821,
      "lng": 35.7234
    }
  },
  "PH-TW": {
    "from": {
      "lat": 21.1224,
      "lng": 121.9507
    },
    "to": {
      "lat": 22.0139,
      "lng": 121.5877
    }
  },
  "HR-IT": {
    "from": {
      "lat": 41.9199,
      "lng": 16.1405
    },
    "to": {
      "lat": 42.7361,
      "lng": 16.8208
    }
  },
  "JP-TW": {
    "from": {
      "lat": 24.5978,
      "lng": 121.8818
    },
    "to": {
      "lat": 24.4548,
      "lng": 122.9382
    }
  },
  "DK-NO": {
    "from": {
      "lat": 57.1229,
      "lng": 8.618
    },
    "to": {
      "lat": 58.102,
      "lng": 8.1229
    }
  },
  "IN-MV": {
    "from": {
      "lat": 7.1072,
      "lng": 72.8838
    },
    "to": {
      "lat": 8.2495,
      "lng": 73.0327
    }
  },
  "GD-TT": {
    "from": {
      "lat": 11.1791,
      "lng": -60.8452
    },
    "to": {
      "lat": 12.0441,
      "lng": -61.6316
    }
  },
  "DM-LC": {
    "from": {
      "lat": 15.2051,
      "lng": -61.3507
    },
    "to": {
      "lat": 14.1119,
      "lng": -60.9335
    }
  },
  "AU-ID": {
    "from": {
      "lat": -9.1061,
      "lng": 140.977
    },
    "to": {
      "lat": -9.2714,
      "lng": 142.1509
    }
  },
  "BZ-HN": {
    "from": {
      "lat": 15.8672,
      "lng": -87.951
    },
    "to": {
      "lat": 17.0231,
      "lng": -88.2235
    }
  },
  "GD-VE": {
    "from": {
      "lat": 10.7448,
      "lng": -61.8648
    },
    "to": {
      "lat": 12.0043,
      "lng": -61.7755
    }
  },
  "GD-LC": {
    "from": {
      "lat": 12.5297,
      "lng": -61.428
    },
    "to": {
      "lat": 13.7147,
      "lng": -60.9551
    }
  },
  "LV-SE": {
    "from": {
      "lat": 57.3926,
      "lng": 18.9263
    },
    "to": {
      "lat": 56.8463,
      "lng": 21.0652
    }
  },
  "BB-LC": {
    "from": {
      "lat": 13.7773,
      "lng": -60.9073
    },
    "to": {
      "lat": 13.3106,
      "lng": -59.6522
    }
  },
  "CU-JM": {
    "from": {
      "lat": 19.8278,
      "lng": -77.6925
    },
    "to": {
      "lat": 18.5234,
      "lng": -77.8161
    }
  },
  "CO-NI": {
    "from": {
      "lat": 12.1818,
      "lng": -83.0211
    },
    "to": {
      "lat": 12.5115,
      "lng": -81.7237
    }
  },
  "EE-SE": {
    "from": {
      "lat": 58.3676,
      "lng": 19.3317
    },
    "to": {
      "lat": 58.511,
      "lng": 21.8324
    }
  }
}
