/**
 * Generates data/flags-wide.gen.ts — a recomposed 3:1 "wide tile" variant of
 * every country flag — from the source SVGs in data/static/flags/. Emblem-
 * bearing flags keep their device undistorted; excluded flags (ensigns,
 * whole-flag diagonals, Nepal) are simply omitted, so the runtime falls back to
 * a contained original for those.
 *
 * This is a standalone Bun generator (like the other generate:* scripts):
 *   bun run generate:flags-wide
 *
 * The recompose engine itself lives in lib/flags/ so the review harness
 * (pages/flags-review.vue) can run the identical logic in the browser.
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { recompose } from '~~/lib/flags/recompose'
import type { ISOCountryCode } from '~~/types/geography.types'

const FLAGS_DIR = 'data/static/flags'
const OUT_FILE = 'data/flags-wide.gen.ts'

const createFlagsWideFile = () => {
  const files = readdirSync(FLAGS_DIR).filter(f => f.endsWith('.svg'))

  const wide: Record<string, string> = {}
  const summary: Record<string, number> = {}

  for (const file of files.sort()) {
    // COUNTRIES (and country.isoCode) are keyed UPPERCASE; flag filenames are
    // lowercase. Use the uppercase iso for BOTH the recompose call (so its
    // OVERRIDES/exclude lookup, which is keyed uppercase, matches) and the
    // emitted map key (so runtime lookups by isoCode hit).
    const iso = file.replace(/\.svg$/, '').toUpperCase() as ISOCountryCode
    const source = readFileSync(`${FLAGS_DIR}/${file}`, 'utf8')
    const result = recompose(iso, source)

    summary[`${result.family}/${result.resolution}`] =
      (summary[`${result.family}/${result.resolution}`] ?? 0) + 1

    if (result.svg) wide[iso] = result.svg
  }

  const output = `
    import type { ISOCountryCode } from '~~/types/geography.types'

    /**
     * Recomposed 3:1 wide-tile flag variants, keyed by ISO code. Generated by
     * generators/flags/create-flags-wide-file.ts — do not edit by hand. Flags
     * that can't be recomposed cleanly are absent; callers fall back to the
     * contained original for those.
     */
    export const FLAGS_WIDE: Partial<Record<ISOCountryCode, string>> = ${JSON.stringify(wide)}
  `

  writeFileSync(OUT_FILE, output)

  const total = files.length
  const emitted = Object.keys(wide).length
  console.log(`Finished creating file: ${OUT_FILE}`)
  console.log(`  recomposed ${emitted}/${total} flags (${total - emitted} excluded → contain-fallback)`)
  console.log('  by family/resolution:')
  for (const [key, count] of Object.entries(summary).sort((a, b) => b[1] - a[1])) {
    console.log(`    ${String(count).padStart(4)}  ${key}`)
  }
}

createFlagsWideFile()
